/* eslint-disable */
/**
 * Generates supabase/migrations/seed_language_packs_and_skeletons.sql
 * from the TS source-of-truth packs + skeletons.
 *
 * Run: npx ts-node --transpile-only scripts/generate-seed-sql.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import ENGLISH from '../data/language-packs/english';
import SHONA from '../data/language-packs/shona';
import LESSON_SKELETONS from '../data/language-packs/skeletons';

function jsonbLiteral(value: unknown): string {
  // PostgreSQL JSONB literal: $$<json>$$::jsonb — dollar-quoted, no escaping.
  return `$$${JSON.stringify(value)}$$::jsonb`;
}

function escSql(s: string): string {
  return s.replace(/'/g, "''");
}

const out: string[] = [];
out.push('-- Seed data: language packs (English, Shona) + 100 lesson skeletons.');
out.push('-- Generated by scripts/generate-seed-sql.ts from the TS source-of-truth.');
out.push('-- Re-running is safe: each statement is idempotent via UPSERT.');
out.push('');
out.push('begin;');
out.push('');

// -------- language_packs --------
out.push('-- language_packs ----------------------------------------------------');
for (const pack of [ENGLISH, SHONA]) {
  out.push(
    `insert into public.language_packs (id, iso_code, display_name, flag_emoji, concepts, lesson_context, ui_strings, metadata) values (`,
  );
  out.push(`  '${escSql(pack.id)}',`);
  out.push(`  '${escSql(pack.iso_code)}',`);
  out.push(`  '${escSql(pack.display_name)}',`);
  out.push(`  '${escSql(pack.flag_emoji)}',`);
  out.push(`  ${jsonbLiteral(pack.concepts)},`);
  out.push(`  ${jsonbLiteral(pack.lesson_context)},`);
  out.push(`  ${jsonbLiteral(pack.ui_strings)},`);
  out.push(`  ${jsonbLiteral(pack.metadata)}`);
  out.push(`)`);
  out.push(`on conflict (id) do update set`);
  out.push(`  iso_code       = excluded.iso_code,`);
  out.push(`  display_name   = excluded.display_name,`);
  out.push(`  flag_emoji     = excluded.flag_emoji,`);
  out.push(`  concepts       = excluded.concepts,`);
  out.push(`  lesson_context = excluded.lesson_context,`);
  out.push(`  ui_strings     = excluded.ui_strings,`);
  out.push(`  metadata       = excluded.metadata,`);
  out.push(`  updated_at     = now();`);
  out.push('');
}

// -------- lesson_skeletons --------
out.push('-- lesson_skeletons -------------------------------------------------');
const skelIds = Object.keys(LESSON_SKELETONS).sort();
for (const id of skelIds) {
  const s = LESSON_SKELETONS[id];
  out.push(
    `insert into public.lesson_skeletons (id, module, lesson, concept_keys, phases, estimated_minutes, xp_reward) values (`,
  );
  out.push(`  '${escSql(s.id)}',`);
  out.push(`  ${s.module},`);
  out.push(`  ${s.lesson},`);
  out.push(`  ${jsonbLiteral(s.concept_keys)},`);
  out.push(`  ${jsonbLiteral(s.phases)},`);
  out.push(`  ${s.estimated_minutes},`);
  out.push(`  ${s.xp_reward}`);
  out.push(`)`);
  out.push(`on conflict (id) do update set`);
  out.push(`  module            = excluded.module,`);
  out.push(`  lesson            = excluded.lesson,`);
  out.push(`  concept_keys      = excluded.concept_keys,`);
  out.push(`  phases            = excluded.phases,`);
  out.push(`  estimated_minutes = excluded.estimated_minutes,`);
  out.push(`  xp_reward         = excluded.xp_reward,`);
  out.push(`  updated_at        = now();`);
  out.push('');
}

out.push('commit;');
out.push('');

const target = path.resolve(__dirname, '..', 'supabase', 'migrations', 'seed_language_packs_and_skeletons.sql');
fs.writeFileSync(target, out.join('\n'));
console.log('Wrote ' + target + ' (' + out.length + ' lines)');
